# Generated by Django 5.2 on 2025-04-20 17:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Работник',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('жизни', models.IntegerField(default=5)),
                ('бонусы', models.IntegerField(default=0)),
                ('выполненные_задачи', models.IntegerField(default=0)),
                ('просроченные_задачи', models.IntegerField(default=0)),
                ('отработанные_часы', models.FloatField(default=0.0)),
                ('зарплата', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('премия', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('пользователь', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Посещаемость',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('дата', models.DateField(default=django.utils.timezone.now)),
                ('время_прихода', models.TimeField(blank=True, null=True)),
                ('опоздание_в_минутах', models.PositiveIntegerField(default=0)),
                ('работник', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.работник')),
            ],
        ),
        migrations.CreateModel(
            name='Задача',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=255)),
                ('срок', models.DateTimeField()),
                ('приоритет', models.CharField(choices=[('низкий', 'Низкий'), ('средний', 'Средний'), ('высокий', 'Высокий')], default='средний', max_length=10)),
                ('оценка', models.IntegerField(default=0)),
                ('потраченное_время_часы', models.FloatField(default=0.0)),
                ('статус', models.CharField(choices=[('в_ожидании', 'В ожидании'), ('в_процессе', 'В процессе'), ('выполнена', 'Выполнена'), ('просрочена', 'Просрочена')], default='в_ожидании', max_length=20)),
                ('опоздание_по_задаче_в_минутах', models.PositiveIntegerField(default=0)),
                ('исполнитель', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='задачи', to='staff.работник')),
                ('постановщик', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='поставленные_задачи', to='staff.работник')),
            ],
        ),
        migrations.CreateModel(
            name='Бонус',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('дата_выдачи', models.DateField(default=django.utils.timezone.now)),
                ('описание', models.TextField()),
                ('сумма', models.DecimalField(decimal_places=2, max_digits=8)),
                ('работник', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.работник')),
            ],
        ),
    ]
