# Generated by Django 5.2 on 2025-04-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_работник_год_рождения_работник_график_работы_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='работник',
            name='должность',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
