# Generated by Django 5.2 on 2025-04-21 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_работник_должность'),
    ]

    operations = [
        migrations.RenameField(
            model_name='задача',
            old_name='потраченное_время_часы',
            new_name='потраченное_время_в_минутах',
        ),
    ]
