# Generated by Django 5.2 on 2025-04-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_rename_потраченное_время_часы_задача_потраченное_время_в_минутах'),
    ]

    operations = [
        migrations.AddField(
            model_name='посещаемость',
            name='время_ухода',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
