# Generated by Django 5.2 on 2025-05-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_посещаемость_время_ухода'),
    ]

    operations = [
        migrations.CreateModel(
            name='Расходы',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=255)),
                ('дата', models.DateField()),
                ('категория', models.CharField(choices=[('закуп', 'Закуп'), ('оплата за смену', 'Оплата за смену')], default='закуп', max_length=20)),
                ('сумма', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='работник',
            name='рабочие_дни',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='работник',
            name='смена',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='работник',
            name='тип_получения_зарплаты',
            field=models.CharField(default='Фиксированное', max_length=500),
        ),
    ]
