# Generated by Django 5.2 on 2025-05-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_расходы_работник_рабочие_дни_работник_смена_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='расходы',
            name='исполнитель',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
